=== Retro-I/Retro.I/settings/schemas/schema_radio-stations.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "RadioStationList",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "color": {
                "type": "string",
                "description": "Hex color code associated with the station (e.g., #00A1D6)",
                "pattern": "^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                "default": "#00FF00"
            },
            "favorite": {
                "type": "boolean",
                "description": "Whether the station is marked as a favorite",
                "default": false
            },
            "id": {
                "type": "string",
                "description": "Unique identifier (UUID)",
                "format": "uuid"
            },
            "logo": {
                "type": "string",
                "description": "Filename or URL of the station logo"
            },
            "name": {
                "type": "string",
                "description": "Display name of the station",
                "default": "Radiosender"
            },
            "src": {
                "type": "string",
                "description": "Stream source URL",
                "format": "uri"
            }
        },
        "required": ["color", "favorite", "id", "logo", "name", "src"],
        "additionalProperties": false
    }
}

=== Retro-I/Retro.I/assets/radio-stations.json
[
  {
    "id": "2a756cf7-35a4-469e-ad09-0afce7913214",
    "color": "#00A1D6",
    "logo": "bayern_1.png",
    "name": "Bayern 1",
    "src": "https://dispatcher.rndfnk.com/br/br1/nbopf/mp3/mid",
    "favorite": false
  },
  {
    "id": "6e761b02-17ad-4142-a08e-745c3c71d4e5",
    "color": "#80CC28",
    "logo": "bayern_3.png",
    "name": "Bayern 3",
    "src": "https://dispatcher.rndfnk.com/br/br3/live/mp3/mid",
    "favorite": false
  },
  {
    "id": "79b48682-c8ec-40b3-80d2-93df6cfd1aa7",
    "color": "#003B82",
    "logo": "br_heimat.png",
    "name": "BR Heimat",
    "src": "https://dispatcher.rndfnk.com/br/brheimat/live/mp3/mid",
    "favorite": false
  },
  {
    "id": "5434163b-40b1-4247-b493-3ccbd19183c2",
    "color": "#FCD51E",
    "logo": "antenne_bayern.png",
    "name": "Antenne Bayern",
    "src": "https://stream.antenne.de/antenne/stream/aacp",
    "favorite": false
  },
  {
    "id": "4eafc2b9-a34a-4f28-be52-9cad638dd63c",
    "color": "#E6001E",
    "logo": "rock_antenne.png",
    "name": "Rock Antenne Bayern",
    "src": "https://stream.antenne.de/rockantenne-bayern/stream/aacp",
    "favorite": false
  },
  {
    "id": "41db5229-9b6c-4e70-8087-5e74f94b8331",
    "color": "#F5B52E",
    "logo": "radio_ramasuri.png",
    "name": "Radio Ramasuri",
    "src": "http://mp3.ramasuri.c.nmdn.net/ps-ramasuri/livestream.mp3",
    "favorite": false
  },
  {
    "id": "21f7820c-6712-4f1e-9923-71200ea31439",
    "color": "#003C65",
    "logo": "radio_galaxy.png",
    "name": "Radio Galaxy",
    "src": "https://edge70.streamonkey.net/fhn-radiogalaxy",
    "favorite": false
  },
  {
    "id": "d6516b8e-924c-456c-941f-605995b432d4",
    "color": "#CC0000",
    "logo": "radio_bob.png",
    "name": "Radio Bob",
    "src": "http://streams.radiobob.de/bob-national/aac-64/mediaplayer",
    "favorite": false
  },
  {
    "id": "49f3ed26-594f-4c20-940c-1c0a36aaf6f3",
    "color": "#CC0000",
    "logo": "radio_dumba.png",
    "name": "Radio Dumba",
    "src": "https://radio-dumba.stream.laut.fm/radio-dumba",
    "favorite": false
  },
  {
    "id": "47281868-96c9-4449-afc9-4f9023cb8883",
    "color": "#700040",
    "logo": "radio_schlagerparadies.png",
    "name": "Radio Schlagerparadies",
    "src": "https://webstream.schlagerparadies.de/schlagerparadies128k.mp3",
    "favorite": false
  },
  {
    "id": "0b82f3df-14a5-4dd7-9787-f2550b5edbeb",
    "color": "#489729",
    "logo": "schlagergarage.png",
    "name": "Schlagergarage",
    "src": "https://stream.laut.fm/schlagergarage",
    "favorite": false
  },
  {
    "id": "6bd7527d-e93d-4156-852c-9ec95cb4f916",
    "color": "#FF6612",
    "logo": "radio_paloma.png",
    "name": "Radio Paloma",
    "src": "http://pool.radiopaloma.de/RADIOPALOMA.mp3",
    "favorite": false
  },
  {
    "id": "eb9c89a4-79ef-4cce-80ce-65a1bb616dbf",
    "color": "#AD0A4F",
    "logo": "sunshine_live_hardstyle.jpg",
    "name": "Sunshine live Hardstyle",
    "src": "https://stream.sunshine-live.de/hardstyle/mp3-192/stream.sunshine-live.de/",
    "favorite": false
  },
  {
    "id": "76620746-f06f-4696-a9a2-e0ea2c335dec",
    "color": "#FF0000",
    "logo": "radio_energy.png",
    "name": "Radio Energy",
    "src": "https://edge61.streamonkey.net/energy-nuernberg?aggregator=shorty",
    "favorite": false
  },
  {
    "id": "42c4899a-747f-462d-8f2b-bf17ad1efe1f",
    "color": "#FF009A",
    "logo": "1_live.png",
    "name": "1 LIVE",
    "src": "https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3",
    "favorite": false
  },
  {
    "id": "f6b486b1-201a-424f-a950-cf1f690260f5",
    "color": "#00928B",
    "logo": "radio_bollerwagen.png",
    "name": "Radio Bollerwagen",
    "src": "https://player.ffn.de/radiobollerwagen.mp3",
    "favorite": false
  },
  {
    "id": "a34db392-6362-4aba-92d8-a8c5b7f59ec0",
    "color": "#CC1033",
    "logo": "absolut_hot.png",
    "name": "Absolut Hot",
    "src": "https://edge67.live-sm.absolutradio.de/absolut-hot",
    "favorite": false
  },
  {
    "id": "2817dfdc-e4a7-4d8a-b586-1d99c3a1c733",
    "color": "#7A949E",
    "logo": "schwarzwaldradio.png",
    "name": "Schwarzwaldradio",
    "src": "https://edge59.streamonkey.net/fho-schwarzwaldradiohifi",
    "favorite": false
  },
  {
    "id": "ddfc49d6-5d7a-4128-bfd4-2b93a89a250c",
    "color": "#6A5F33",
    "logo": "https://www.technobase.fm/content/images/site/logo-technobase.fm.png",
    "name": "TechnoBase.FM",
    "src": "https://listen.technobase.fm/tunein-mp3",
    "favorite": false
  },
  {
    "id": "8d12e263-be73-412b-856b-6d8484313cf0",
    "color": "#FFDD00",
    "logo": "chari_vari.png",
    "name": "Chari Vari",
    "src": "https://live.stream.charivari.de/955charivari-webradio?aggregator=charivari_de_link",
    "favorite": false
  },
  {
    "id": "9c93f954-a5ce-4557-a32e-0cfb3f5d78cb",
    "color": "#014C6B",
    "logo": "chillout_antenne.png",
    "name": "Chillout Antenne",
    "src": "https://s5-webradio.antenne.de/chillout/stream/mp3",
    "favorite": false
  },
  {
    "id": "3428a55c-5215-4579-a1a9-86ca76ac56e4",
    "color": "#2C9BD3",
    "logo": "antenne_adria.png",
    "name": "Antenne Adria",
    "src": "https://antenne-adria.stream.laut.fm/antenne-adria",
    "favorite": false
  },
  {
    "id": "b442f2f4-239d-4d4a-ad12-3d22e9c6daa7",
    "color": "#104484",
    "logo": "wacken_radio.png",
    "name": "Wacken Radio",
    "src": "https://wacken.stream.laut.fm/wacken",
    "favorite": false
  },
  {
    "id": "f967d487-359b-4d50-9f79-4271ada52236",
    "color": "#167EBE",
    "logo": "radio_bob_mittelalter.png",
    "name": "Radio Bob Mittelalter",
    "src": "http://streams.radiobob.de/mittelalter/mp3-192/mediaplayer",
    "favorite": false
  },
  {
    "id": "58dca9c7-ac98-4c67-a990-93820fef186e",
    "color": "#FFE31B",
    "logo": "fluxfm.png",
    "name": "FluxFM",
    "src": "http://channels.fluxfm.de/FluxFM/stream.mp3",
    "favorite": false
  },
  {
    "id": "e7e872db-bfb8-47f7-b535-9f46a354ae5b",
    "color": "#BC941F",
    "logo": "blasmusik_radio.png",
    "name": "Blasmusik Radio",
    "src": "https://stream.laut.fm/blasmusikradio",
    "favorite": false
  }
]

=== Retro-I/Retro.I/settings/radio-stations.json
[
    {
        "color": "#00A1D6",
        "favorite": false,
        "id": "2a756cf7-35a4-469e-ad09-0afce7913214",
        "logo": "https://api.ardmediathek.de/image-service/images/urn:ard:image:b366004f6196d70c?w=512",
        "name": "Bayern 1",
        "src": "https://dispatcher.rndfnk.com/br/br1/nbopf/mp3/mid"
    },
    {
        "color": "#80CC28",
        "favorite": false,
        "id": "6e761b02-17ad-4142-a08e-745c3c71d4e5",
        "logo": "https://api.ardmediathek.de/image-service/images/urn:ard:image:52fd25fc45de7c6a?w=512",
        "name": "Bayern 3",
        "src": "https://dispatcher.rndfnk.com/br/br3/live/mp3/mid"
    },
    {
        "color": "#003B82",
        "favorite": false,
        "id": "79b48682-c8ec-40b3-80d2-93df6cfd1aa7",
        "logo": "https://api.ardmediathek.de/image-service/images/urn:ard:image:37a3d50efe6feacb?w=512",
        "name": "BR Heimat",
        "src": "https://dispatcher.rndfnk.com/br/brheimat/live/mp3/mid"
    },
    {
        "color": "#FCD51E",
        "favorite": false,
        "id": "5434163b-40b1-4247-b493-3ccbd19183c2",
        "logo": "https://www.antenne.de/logos/station-antenne-bayern/apple-touch-icon.png",
        "name": "Antenne Bayern",
        "src": "https://stream.antenne.de/antenne/stream/aacp"
    },
    {
        "color": "#E6001E",
        "favorite": false,
        "id": "4eafc2b9-a34a-4f28-be52-9cad638dd63c",
        "logo": "http://www.rockantenne.de/logos/station-rock-antenne/apple-touch-icon.png",
        "name": "Rock Antenne Bayern",
        "src": "https://stream.antenne.de/rockantenne-bayern/stream/aacp"
    },
    {
        "color": "#F5B52E",
        "favorite": false,
        "id": "41db5229-9b6c-4e70-8087-5e74f94b8331",
        "logo": "https://www.ramasuri.de/storage/thumbs/192x192/r:1712659775/174120.png",
        "name": "Radio Ramasuri",
        "src": "https://ramasuri.radioho.st/ramasuri-live/mp3-192/"
    },
    {
        "color": "#003C65",
        "favorite": false,
        "id": "21f7820c-6712-4f1e-9923-71200ea31439",
        "logo": "https://amberg-weiden.radiogalaxy.de/storage/thumbs/192x192/r:1677262065/17728.png",
        "name": "Radio Galaxy",
        "src": "https://edge01.streamonkey.net/fhn-radiogalaxy/stream/mp3"
    },
    {
        "color": "#CC0000",
        "favorite": false,
        "id": "d6516b8e-924c-456c-941f-605995b432d4",
        "logo": "https://www.radiowoche.de/wp-content/uploads/2025/05/Neues-BOB-Logo-2025.jpg",
        "name": "Radio Bob",
        "src": "http://streams.radiobob.de/bob-national/aac-64/mediaplayer"
    },
    {
        "color": "#CC0000",
        "favorite": false,
        "id": "49f3ed26-594f-4c20-940c-1c0a36aaf6f3",
        "logo": "http://www.radiodumba.de/.cm4all/sysdb/favicon/icon-120x120_de1a736.png",
        "name": "Radio Dumba",
        "src": "https://radio-dumba.stream.laut.fm/radio-dumba"
    },
    {
        "color": "#700040",
        "favorite": false,
        "id": "47281868-96c9-4449-afc9-4f9023cb8883",
        "logo": "https://schlagerparadies.de/images/rsp_setup/apple-icon-180x180.png",
        "name": "Radio Schlagerparadies",
        "src": "https://webstream.schlagerparadies.de/schlagerparadies128k.mp3"
    },
    {
        "color": "#FF6612",
        "favorite": false,
        "id": "6bd7527d-e93d-4156-852c-9ec95cb4f916",
        "logo": "https://www.radiopaloma.de/wp-content/themes/cmms-theme-radio_paloma/assets/img/logo.svg",
        "name": "Radio Paloma",
        "src": "http://pool.radiopaloma.de/RADIOPALOMA.mp3"
    },
    {
        "color": "#AD0A4F",
        "favorite": false,
        "id": "eb9c89a4-79ef-4cce-80ce-65a1bb616dbf",
        "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Sunshine_live_Logo_2022.svg/640px-Sunshine_live_Logo_2022.svg.png",
        "name": "Sunshine live Hardstyle",
        "src": "https://stream.sunshine-live.de/hardstyle/mp3-192/stream.sunshine-live.de/"
    },
    {
        "color": "#FF0000",
        "favorite": false,
        "id": "76620746-f06f-4696-a9a2-e0ea2c335dec",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQAT-AV4CT86_3eXzqIO-mpkjPpEBKIlQK9A&s",
        "name": "Radio Energy",
        "src": "https://edge61.streamonkey.net/energy-nuernberg?aggregator=shorty"
    },
    {
        "color": "#FF009A",
        "favorite": false,
        "id": "42c4899a-747f-462d-8f2b-bf17ad1efe1f",
        "logo": "https://www1.wdr.de/resources/img/wdr/logo/epgmodule/1live_logo_claim.svg",
        "name": "1 LIVE",
        "src": "https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3"
    },
    {
        "color": "#00928B",
        "favorite": false,
        "id": "f6b486b1-201a-424f-a950-cf1f690260f5",
        "logo": "https://www.ffn.de/fileadmin/ffn.de/musik/streams/bollerwagen.png",
        "name": "Radio Bollerwagen",
        "src": "https://player.ffn.de/radiobollerwagen.mp3"
    },
    {
        "color": "#CC1033",
        "favorite": false,
        "id": "a34db392-6362-4aba-92d8-a8c5b7f59ec0",
        "logo": "https://www.radio.de/175/absoluthot.png?version=3b0437d8076d127077a322e2b4903ec3443ab5b4",
        "name": "Absolut Hot",
        "src": "https://edge67.live-sm.absolutradio.de/absolut-hot"
    },
    {
        "color": "#7A949E",
        "favorite": false,
        "id": "2817dfdc-e4a7-4d8a-b586-1d99c3a1c733",
        "logo": "https://schwarzwaldradio.s3-cdn.welocal.cloud/sources/30_0bilp1tabhdfc_nr9lh28cs6ggk.svg",
        "name": "Schwarzwaldradio",
        "src": "https://edge59.streamonkey.net/fho-schwarzwaldradiohifi"
    },
    {
        "color": "#6A5F33",
        "favorite": false,
        "id": "ddfc49d6-5d7a-4128-bfd4-2b93a89a250c",
        "logo": "https://www.technobase.fm/content/images/site/logo-technobase.fm.png",
        "name": "TechnoBase.FM",
        "src": "https://listen.technobase.fm/tunein-mp3"
    },
    {
        "color": "#FFDD00",
        "favorite": false,
        "id": "8d12e263-be73-412b-856b-6d8484313cf0",
        "logo": "https://myonlineradio.de/public/uploads/radio_img/95-5-charivari/play_250_250.webp",
        "name": "Chari Vari",
        "src": "https://live.stream.charivari.de/955charivari-webradio?aggregator=charivari_de_link"
    },
    {
        "color": "#014C6B",
        "favorite": false,
        "id": "9c93f954-a5ce-4557-a32e-0cfb3f5d78cb",
        "logo": "https://www.antenne.de/media/cache/3/version/59534/chillout-antenne-aggregatoren-800x800-v1.png/525ec93a8f7e5f28.webp",
        "name": "Chillout Antenne",
        "src": "https://s5-webradio.antenne.de/chillout/stream/mp3"
    },
    {
        "color": "#2C9BD3",
        "favorite": false,
        "id": "3428a55c-5215-4579-a1a9-86ca76ac56e4",
        "logo": "https://www.radio.de/300/lautfm-antenne-adria.jpeg?version=2f9f300e3ce58d2bb7d2a4f5ab5a951ebb0d1c3a",
        "name": "Antenne Adria",
        "src": "https://antenne-adria.stream.laut.fm/antenne-adria"
    },
    {
        "color": "#104484",
        "favorite": false,
        "id": "b442f2f4-239d-4d4a-ad12-3d22e9c6daa7",
        "logo": "https://images.radiobob.de/files/2025-07/bob_wackenradio_stream_tile_mit_schrift.jpg?width=360&height=360",
        "name": "Wacken Radio",
        "src": "https://wacken.stream.laut.fm/wacken"
    },
    {
        "color": "#167EBE",
        "favorite": false,
        "id": "f967d487-359b-4d50-9f79-4271ada52236",
        "logo": "https://images.radiobob.de/files/2025-05/mittelalter_rock_stream_schrift.jpg",
        "name": "Radio Bob Mittelalter",
        "src": "http://streams.radiobob.de/mittelalter/mp3-192/mediaplayer"
    },
    {
        "color": "#BC941F",
        "favorite": false,
        "id": "e7e872db-bfb8-47f7-b535-9f46a354ae5b",
        "logo": "https://assets.laut.fm/519f4bd65dccf6120ae835bc5e55488f?t=_640x640",
        "name": "Blasmusik Radio",
        "src": "https://stream.laut.fm/blasmusikradio"
    }
]
