=== Retro-I/Retro.I/settings/schemas/schema_favorite-sounds.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "FavoriteStations",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "type": "string",
                "description": "id of the sound (from api)"
            },
            "title": {
                "type": "string",
                "description": "Displayed title of the sound"
            },
            "url": {
                "type": "string",
                "description": "The link to instant buttons",
                "format": "uri"
            },
            "mp3": {
                "type": "string",
                "description": "The actual mp3 sound",
                "format": "uri"
            }
        },
        "required": ["id", "title", "url", "mp3"],
        "additionalProperties": false
    }
}

=== Retro-I/Retro.I/assets/favorite_sounds.json
[
    {
        "id": "hog-rider-extra-loud-6366",
        "title": "hog rider extra loud",
        "url": "https://www.myinstants.com/en/instant/hog-rider-extra-loud-6366",
        "mp3": "https://www.myinstants.com/media/sounds/hog-rider-extra-loud.mp3"
    },
    {
        "id": "asdfmovie-oh-54832",
        "title": "ASDFmovie oh",
        "url": "https://www.myinstants.com/en/instant/asdfmovie-oh-54832",
        "mp3": "https://www.myinstants.com/media/sounds/asdfmovie-oh.mp3"
    },
    {
        "id": "asdfmovie-oh-54832",
        "title": "ASDFmovie oh",
        "url": "https://www.myinstants.com/en/instant/asdfmovie-oh-54832",
        "mp3": "https://www.myinstants.com/media/sounds/asdfmovie-oh.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    },
    {
        "id": "fart-button",
        "title": "Fart Button",
        "url": "https://www.myinstants.com/en/instant/fart-button",
        "mp3": "https://www.myinstants.com/media/sounds/perfect-fart.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    },
    {
        "id": "fart",
        "title": "Fart",
        "url": "https://www.myinstants.com/en/instant/fart",
        "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
    }
]
